// Code generated by "genlifx"; DO NOT EDIT.
package lan

type LightHsbk struct {
	Hue        uint16
	Saturation uint16
	Brightness uint16
	Kelvin     uint16
}

type MultiZoneEffectParameter struct {
	Parameter0 uint32
	Parameter1 uint32
	Parameter2 uint32
	Parameter3 uint32
	Parameter4 uint32
	Parameter5 uint32
	Parameter6 uint32
	Parameter7 uint32
}

type MultiZoneEffectSettings struct {
	Instanceid uint32
	Type       MultiZoneEffectType
	Speed      uint32
	Duration   uint64
	Parameter  MultiZoneEffectParameter
}

type TileAccelMeas struct {
	X int16
	Y int16
	Z int16
}

type TileBufferRect struct {
	X     uint8
	Y     uint8
	Width uint8
}

type TileEffectParameter struct {
	Parameter0 uint32
	Parameter1 uint32
	Parameter2 uint32
	Parameter3 uint32
	Parameter4 uint32
	Parameter5 uint32
	Parameter6 uint32
	Parameter7 uint32
}

type TileEffectSettings struct {
	Instanceid   uint32
	Type         TileEffectType
	Speed        uint32
	Duration     uint64
	Reserved0    uint32
	Reserved1    uint32
	Parameter    TileEffectParameter
	PaletteCount uint8
	Palette      [16]LightHsbk
}

type TileStateDevice struct {
	AccelMeas     TileAccelMeas
	UserX         float32
	UserY         float32
	Width         uint8
	Height        uint8
	DeviceVersion DeviceStateVersion
	Firmware      DeviceStateHostFirmware
}
